<?php namespace GrahamCampbell\BootstrapCMS\Providers\Common;

/**
 * This file is part of Bootstrap CMS by Graham Campbell.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * @package    Bootstrap-CMS
 * @author     Graham Campbell
 * @license    GNU AFFERO GENERAL PUBLIC LICENSE
 * @copyright  Copyright (C) 2013  Graham Campbell
 * @link       https://github.com/GrahamCampbell/Bootstrap-CMS
 */

trait TraitPaginateProvider {

    /**
     * The paginate links generated by the paginate method.
     *
     * @var string
     */
    protected $paginatelinks;

    /**
     * Get a paginated list of the models.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function paginate() {
        $model = $this->model;

        if (property_exists($model, 'order')) {
            $values = $model::orderBy($model::$order, $model::$sort)->paginate($model::$paginate, $model::$index);
        } else {
            $values = $model::paginate($model::$paginate, $model::$index);
        }

        if (count($values) != 0) {
            $this->paginatelinks = $values->links();
        } else {
            $this->paginatelinks = '';
        }

        return $values;
    }

    /**
     * Get the paginate links.
     *
     * @return string
     */
    public function links() {
        return $this->paginatelinks;
    }
}
