<?php namespace GrahamCampbell\BootstrapCMS\Providers\Common;

trait TraitPaginateProvider {

    /**
     * The paginate links generated by the paginate method.
     *
     * @var string
     */
    protected $paginatelinks;

    /**
     * Get a paginated list of the models.
     *
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function paginate() {
        $model = $this->model;

        if (property_exists($model, 'order')) {
            $values = $model::orderBy($model::$order, $model::$sort)->paginate($model::$paginate, $model::$index);
        } else {
            $values = $model::paginate($model::$paginate, $model::$index);
        }

        if (count($values) != 0) {
            $this->paginatelinks = $values->links();
        } else {
            $this->paginatelinks = '';
        }

        return $values;
    }

    /**
     * Get the paginate links.
     *
     * @return string
     */
    public function links() {
        return $this->paginatelinks;
    }
}
